FROM python:3.11-slim

WORKDIR /app

COPY requirments.txt .
COPY app.py .
COPY ingest.py .
COPY rag.py .

RUN pip install --no-cache-dir -r requirments.txt

RUN mkdir -p /data


EXPOSE 7860

CMD ["python", "app.py"]
